const fs = require('fs');
const es = JSON.parse(fs.readFileSync('src/assets/i18n/es.json', 'utf8'));
const en = JSON.parse(fs.readFileSync('src/assets/i18n/en.json', 'utf8'));

function merge(objEs, objEn) {
  if (typeof objEs !== 'object' || objEs === null) {
    return objEn !== undefined ? objEn : objEs;
  }
  if (Array.isArray(objEs)) {
    return objEs.map((item, index) => merge(item, objEn ? objEn[index] : undefined));
  }
  const result = {};
  for (let key in objEs) {
    result[key] = merge(objEs[key], objEn ? objEn[key] : undefined);
  }
  return result;
}

const merged = merge(es, en);

// ACCESSIBLE_PROGRAMMING fixes and translations
merged.ACCESSIBLE_PROGRAMMING.PYTHON_TITLE = 'Code-Based Programming (Micro:bit Python Editor)';
merged.ACCESSIBLE_PROGRAMMING.PYTHON_P1 = 'As an alternative to block-based programming, code-based programming (microPython or JavaScript) can be used. This type of programming, being plain text, is highly accessible to screen readers.';
merged.ACCESSIBLE_PROGRAMMING.PYTHON_P2 = 'The problem with this type of programming is that users must have a minimum knowledge of the programming language, so they have to be taught the language and concepts at the same time. This does not happen with block-based programming, as language knowledge is not necessary and the main concepts worked on are programming concepts like variables, constants, loops, etc.';
merged.ACCESSIBLE_PROGRAMMING.PYTHON_P3 = 'The only procedure currently available to minimize this barrier (language knowledge) is the creation of programming blocks where the student only has to replace or complete part of the code. Creating the skeleton of programming blocks in code would be the only current option to guarantee 100% access via a screen reader.';
merged.ACCESSIBLE_PROGRAMMING.PYTHON_P4 = 'Promoting accessible programming not only benefits people with disabilities, but also improves the experience for all users, promoting a culture of inclusive design in technology.';
merged.ACCESSIBLE_PROGRAMMING.PYTHON_P5 = 'Below are two examples: one where the Micro:bit\'s response is only through the screen, and another, more accessible one, where the information output is through the screen and reinforced with sound output.';

if (merged.ACCESSIBLE_PROGRAMMING.CODE_L1_P) {
  merged.ACCESSIBLE_PROGRAMMING.CODE_L1_P = merged.ACCESSIBLE_PROGRAMMING.CODE_L1_P.replace('gmae', 'game').replace('fos', 'for').replace('an another', 'and another');
}
if (merged.ACCESSIBLE_PROGRAMMING.CODE_L3_P) {
  merged.ACCESSIBLE_PROGRAMMING.CODE_L3_P = merged.ACCESSIBLE_PROGRAMMING.CODE_L3_P.replace('prgrams', 'programs').replace('posible', 'possible').replace('secuences', 'sequences').replace('memroy', 'memory').replace('dificulties', 'difficulties');
}
if (merged.ACCESSIBLE_PROGRAMMING.CODE_L4_P) {
  merged.ACCESSIBLE_PROGRAMMING.CODE_L4_P = merged.ACCESSIBLE_PROGRAMMING.CODE_L4_P.replace('idealy', 'ideally').replace('pictogrames', 'pictograms');
}

// EDUCADORES_PAGE top level keys
merged.EDUCADORES_PAGE.DUA = 'UDL';
merged.EDUCADORES_PAGE.DUABBR = 'Universal Design for Learning';

// EDUCADORES_PAGE.MODULES.dua
const dua = merged.EDUCADORES_PAGE.MODULES.dua;
dua.title = 'in this manual';
dua.desc = 'The framework';
dua.desc1 = ': its 3 principles and how to read the markers in this manual.';
dua.badge1 = 'Theoretical framework';
dua.badge2 = '3 principles';
dua.badge3 = 'Practical application';
dua.p1 = 'The';
dua.p11 = 'is a scientific and pedagogical framework that starts from a simple premise:';
dua.p1s = 'there is no average student';
dua.p1c = '. Each person learns differently, has different entry points to knowledge and is motivated by different things. Designing thinking about diversity from the beginning —not as a later patch— is what';
dua.p1c1 = 'proposes.';
dua.p2 = 'This manual integrates';
dua.p21 = 'transversally. It is not an appendix or a separate section: the adaptations are within the exercises themselves, examples and didactic orientations.';
dua.hd2 = 'The three principles of';
dua.p3 = 'Offer information in various ways: text, image, sound, physical demonstration, video, code. No student is excluded by their way of processing information.';
dua.p4s = ' Programming guidelines:';
dua.p4 = 'everyday metaphors, combination of screen and physical board, visual glossary, code with comments in English.';
dua.p5 = 'Provide options to demonstrate what has been learned: not only written text, but also orality, video, physical prototype, diagram, portfolio. The student chooses how they express themselves.';
dua.p6s = 'Programming guidelines:';
dua.p6 = 'code templates, pseudocode, drawn diagram, oral explanation, support tools like the simulator and autocomplete.';
dua.p7 = 'Capture and maintain interest and motivation: choice of context and theme, graded challenges, connection with personal interests, learning community.';
dua.p8s = 'Programming guidelines:';
dua.p8 = 'the student chooses the project theme, real personal data, culture of error, visible and optional challenges, celebration of partial achievements.';
dua.hd3 = 'How to read the markers';
dua.hd31 = 'in this manual';
dua.p9 = 'Throughout all the chapters you will find three types of';
dua.p91 = 'collapsible blocks next to the exercises and explanations. Click to expand them:';
dua.l11 = 'Alternative visual material, explained vocabulary, analogies, audio options.';
dua.l12 = 'Unplugged activities before opening the editor.';
dua.l13 = 'Classroom glossary with pictograms next to each technical term.';
dua.l21 = 'Alternatives to code writing: template with gaps, pseudocode, drawn diagram.';
dua.l22 = 'Forms of presentation: oral, 60-second video, card portfolio.';
dua.l23 = 'Support tools: simulator, autocomplete, reference integrated in the editor.';
dua.l31 = 'Choice of context: the student chooses the theme of the project.';
dua.l32 = 'Challenges with graded difficulty (Level 1 → 3) visible to all.';
dua.l33 = 'Immediate feedback from the micro:bit: the result is seen instantly.';
dua.l41 = 'The';
dua.l411 = 'is not synonymous with lowering the level. It is to guarantee that everyone can reach it through different paths.';
dua.l42 = 'It is not necessary to apply the three markers in each exercise: select the most relevant ones for your group.';
dua.l43 = 'The markers';
dua.l431 = 'are not';
dua.l432 = 'for students with special needs';
dua.l433 = ': they are for the whole class group, because we all learn differently.';
dua.hd4 = 'Why';
dua.hd41 = 'in programming?';
dua.p10 = 'Programming is historically presented as an activity for';
dua.p101 = 'those who have the head for it';
dua.p102 = 'The';
dua.p103 = 'debunks this idea: anyone can learn to program if given the right access.';
dua.tablecaption = 'Barriers resolved by programming';
dua.th1 = 'Common barrier';
dua.th2 = 'Response';
dua.tr11 = 'Dyslexia and reading difficulties';
dua.tr12 = 'Code with extensive comments, physical metaphors, numbered steps, sans-serif fonts.';
dua.abretdah = 'Attention Deficit Hyperactivity Disorder';
dua.tdah = 'ADHD';
dua.tr21 = 'and attentional difficulties';
dua.tr22 = 'Short sessions with visible product at the end, immediate feedback from the board, option of individual or pair work.';
dua.tr31 = 'High abilities';
dua.tr32 = 'Open challenges without a ceiling (Level 3 or ';
dua.trico = 'rocket';
dua.tr321 = ' challenges), role of peer tutor, autonomous research projects.';
dua.tr41 = 'Technological anxiety';
dua.tr42 = 'Always start with the simulator before the physical board, normalize error, same start routine in all sessions.';
dua.tr51 = 'Motor difficulties';
dua.tr52 = 'Dictation to a classmate, code templates with gaps, operating system voice recognition.';
dua.tr61 = 'Language barrier';
dua.tr62 = 'The code uses simple English words. Create a bilingual glossary with the group: English-Spanish-mother tongue.';

// MODULES.cap1
const cap1 = merged.EDUCADORES_PAGE.MODULES.cap1;
cap1.hd1 = '1.1 Necessary material';
cap1.l11 = 'micro:bit v1 or v2';
cap1.l111 = ': v2 has built-in microphone and speaker.';
cap1.l12 = 'USB Cable';
cap1.l121 = ': standard micro-USB to USB-A.';
cap1.l13 = 'Computer or tablet';
cap1.l131 = ': with a modern browser.';
cap1.l14 = 'Online editor python.microbit.org';
cap1.l141 = ': free, no installation required.';
cap1.l15 = 'Optional: AA or Lithium-Polymer battery pack for portable projects.';
cap1.p1 = 'The micro:bit v2 is recommended for 5th grade Primary and up for its audio capabilities.';
cap1.p2 = 'For large groups, a set of 6-8 micro:bits shared in rotation is sufficient for workshops of 30 students.';
cap1.p3 = 'The ';
cap1.p31 = 'also works on tablets with Bluetooth keyboards.';
cap1.l21 = 'Physical accessibility:';
cap1.l211 = 'verify that the space allows access for students in wheelchairs. The micro:bit can be handled with one hand or with large button adapters.';
cap1.l22 = 'Low vision:';
cap1.l221 = 'zoom the editor interface to 150% with Ctrl/Cmd +; use Ctrl/Cmd 0 to restore.';
cap1.l23 = 'Hearing impairment:';
cap1.l231 = 'sounds are optional; students with hearing impairment can work only with LEDs without losing content.';
cap1.hd2 = '1.2 The Online MicroPython Editor';
cap1.p4 = 'Visit the';
cap1.p41 = 'from any browser. No account or installation required.';
cap1.tablecaption1 = 'Visual layout of the python editor for micro:bit';
cap1.tr111 = 'Editor Area';
cap1.tr112 = 'Function';
cap1.tr113 = 'What you will use it for';
cap1.tr121 = 'Left panel';
cap1.tr122 = 'Python code writing area';
cap1.tr123 = 'Write and edit programs';
cap1.tr131 = 'Simulator';
cap1.tr132 = 'Preview of the micro:bit';
cap1.tr133 = 'Test without a physical board';
cap1.tr141 = 'Bottom console';
cap1.tr142 = 'Messages, errors and print()';
cap1.tr143 = 'Debug the code';
cap1.tr151 = '\'Flash\' button';
cap1.tr152 = 'Sends the code to the real micro:bit';
cap1.tr153 = 'Load the program';
cap1.tr161 = '\'Download\' button';
cap1.tr162 = 'Saves the .hex to the computer';
cap1.tr163 = 'Save projects';
cap1.tr171 = 'Reference';
cap1.abreapi = 'Application Programming Interface';
cap1.tr172 = 'Documentation of all functions';
cap1.tr173 = 'Consultation during class';
cap1.hd3 = '1.3 Your first program: Hello, micro:bit!';
cap1.p5 = 'Write the following code in the editor and press Flash to send it to the board:';
cap1.code = 'hello_world.py';
cap1.captiontable2 = 'Code explanation';
cap1.tr211 = 'Code line';
cap1.tr212 = 'What does it do?';
cap1.tr221 = '# My first program...';
cap1.tr222 = 'Comment: note for the programmer. Python ignores it completely.';
cap1.tr231 = 'from microbit import *';
cap1.tr232 = 'Imports all micro:bit functions. MUST always be the first line.';
cap1.tr241 = 'display.scroll(\'Hello world!\')';
cap1.tr242 = 'Scrolls text across the LED screen from right to left.';
cap1.l31 = 'Metaphor:';
cap1.l311 = 'explain the program as a recipe: first you say where you get the ingredients from (';
cap1.l312 = '), then you give the steps (';
cap1.l313 = 'display.scroll';
cap1.l314 = ').';
cap1.l32 = 'Multimodal:';
cap1.l321 = 'before writing, have the students \'act out\' the program: one says \'Hello world\' while another writes it letter by letter on the board, simulating scrolling.';
cap1.l33 = 'Glossary:';
cap1.l331 = 'add a poster to the classroom with the new terms: import, display, scroll. Use pictograms next to the words.';
cap1.hd4 = '1.4 Predefined images';
cap1.code2 = 'basic_images.py';
cap1.code3 = 'sleep(ms)';
cap1.p6 = 'Wait';
cap1.code4 = 'ms';
cap1.p61 = 'milliseconds (1000 = 1 second).';
cap1.p7 = 'Image bank: Image.HAPPY, Image.SAD, Image.SURPRISED, Image.ANGRY, Image.YES, Image.NO, Image.HEART, Image.DIAMOND, Image.SKULL, Image.ARROW_N...';
cap1.p8 = 'Consult the full reference at python.microbit.org:';
cap1.p81 = 'Reference';
cap1.arrowico = 'go to';
cap1.p82 = 'Image';
cap1.hd5 = 'Emotional story';
cap1.p9 = 'Create a sequence of at least';
cap1.p91 = '5 images';
cap1.p92 = 'that tell a story.';
cap1.p10 = 'Use';
cap1.p101 = 'sleep()';
cap1.p102 = 'so that each image lasts a different time.';
cap1.p11 = 'Example:';
cap1.p111 = 'HAPPY';
cap1.p112 = 'HEART';
cap1.p113 = 'SAD';
cap1.p114 = 'NO';
cap1.p115 = 'HAPPY';
cap1.p12 = 'Advanced level:';
cap1.p121 = 'add';
cap1.p122 = 'display.scroll(\'The End\')';
cap1.p123 = 'at the end.';

// MODULES.cap2
const cap2 = merged.EDUCADORES_PAGE.MODULES.cap2;
cap2.hd1 = '2.1 What is a variable?';
cap2.p1 = 'A variable is like a';
cap2.p11 = 'labeled box';
cap2.p12 = 'where we store information. We can put things in the box, change them or take them out to use them.';
cap2.l11 = 'Physical metaphor:';
cap2.l111 = 'bring real cardboard boxes to the classroom labeled with paper. Put physical objects in and show how to \'change the value\' = change what is inside.';
cap2.l12 = '6-9 years analogy:';
cap2.l121 = 'a variable is like the classroom closet: it has your name (label) and inside you keep what you want.';
cap2.l13 = 'Multimodal:';
cap2.l131 = 'draw the box–label–value diagram on the board for each type before showing the code.';
cap2.hd2 = '2.2 Basic data types';
cap2.capttable = 'Basic variables';
cap2.hr11 = 'Type';
cap2.hr12 = 'What does it contain? (Example)';
cap2.hr21 = 'int (integer)';
cap2.hr22 = 'Whole numbers without decimals: 0, 5, -3, 100';
cap2.hr31 = 'float (decimal)';
cap2.hr32 = 'Numbers with decimals: 3.14, -0.5, 36.7';
cap2.hr41 = 'str (text / string)';
cap2.hr42 = 'Text in quotes: \'Hello\', \'micro:bit\'';
cap2.hr51 = 'bool (boolean)';
cap2.hr52 = 'Only True or False';
cap2.code1 = 'basic_variables.py';
cap2.p2 = 'To show a number on the LEDs it must be converted to text with';
cap2.p21 = 'str().';
cap2.p3 = 'display.scroll(5)';
cap2.p31 = 'will give an error. The correct way:';
cap2.p32 = 'display.scroll(str(5)).';
cap2.hd3 = '2.3 Mathematical operations';
cap2.code2 = 'operations.py';
cap2.ex = 'Exercise: Calculator on the micro:bit';
cap2.p4 = 'Define two numeric variables:';
cap2.p41 = 'num1';
cap2.p42 = 'and';
cap2.p43 = 'num2';
cap2.p5 = 'Calculate their sum, subtraction, product and division.';
cap2.p6 = 'Show each result on the LED screen with a prefix (+, -, x, /).';
cap2.l21 = 'Template (support level):';
cap2.l211 = 'num1 =';
cap2.l212 = 'num2 =';
cap2.l213 = 'sum =';
cap2.l214 = 'display.scroll(\'+\' + str';
cap2.l22 = 'Advanced extension:';
cap2.l221 = 'convert the division result to 1 decimal with';
cap2.l222 = 'round(result, 1)';
cap2.hd4 = '2.4 Reading the temperature sensor';
cap2.p7 = 'The micro:bit has a temperature sensor integrated into the processor:';
cap2.code3 = 'thermometer.py';
cap2.hd5 = 'Key concept';
cap2.p8 = 'temperature()';
cap2.p81 = 'returns the chip temperature (±2 °C error). For environment, subtract 3 degrees.';
cap2.p9 = 'The micro:bit v2 also has a microphone with';
cap2.p91 = 'microphone.sound_level()';

// MODULES.cap3
const cap3 = merged.EDUCADORES_PAGE.MODULES.cap3;
cap3.hd1 = '3.1 The if / elif / else structure';
cap3.p1 = 'Conditionals allow the program to make decisions based on a condition. It is like a traffic light: if the light is red, stop; if it is green, go.';
cap3.l11 = 'Physical activity (unplugged):';
cap3.l111 = 'the educator gives instructions to the students: \'IF you are wearing sneakers';
cap3.l112 = 'then';
cap3.l113 = 'stand up; ELSE';
cap3.l114 = 'stay seated\'. They have lived the conditional with their bodies.';
cap3.l12 = 'Flowchart:';
cap3.l121 = 'draw a decision diamond on the board with YES or NO before opening the editor.';
cap3.l13 = 'Real connection:';
cap3.l131 = 'traffic lights, subway turnstiles, automatic door opening sensors.';
cap3.code1 = 'temperature_conditional.py';
cap3.hd2 = 'Python Rules';
cap3.l21 = 'INDENTATION:';
cap3.l211 = 'the code inside the if is indented 4 spaces. In Python it is MANDATORY';
cap3.l22 = 'if condition:';
cap3.l221 = 'be careful';
cap3.l222 = 'the colon is mandatory';
cap3.l23 = 'code_if_true';
cap3.l231 = 'only executes if the condition is True.';
cap3.l24 = 'else:';
cap3.l241 = 'optional: what to do if the condition is False.';
cap3.hd3 = '3.2 Comparison and logical operators';
cap3.captable = 'Logical operators';
cap3.hr11 = 'Operator';
cap3.hr12 = 'Meaning (Example)';
cap3.hr21 = '==';
cap3.hr22 = 'Equal to: x == 5 (is x equal to 5?)';
cap3.ht31 = '!=';
cap3.hr32 = 'Not equal to: x != 0';
cap3.hr41 = '> and <';
cap3.hr42 = 'Greater or less than: x > 10';
cap3.hr51 = '>= and <=';
cap3.hr52 = 'Greater or equal / less or equal: x >= 18';
cap3.hr61 = 'and (&)';
cap3.hr62 = 'Logical AND: x > 0 & x < 10 (both true)';
cap3.hr71 = 'or (|)';
cap3.hr72 = 'Logical OR: x < 0 or x > 100 (at least one true)';
cap3.hr81 = 'not';
cap3.hr82 = 'Negation: not button_a.is_pressed()';
cap3.hd4 = '3.3 A and B buttons';
cap3.code2 = 'emotions_buttons.py';
cap3.code3 = 'rock_paper_scissors.py';
cap3.p2 = 'is_pressed()';
cap3.p21 = 'returns';
cap3.p22 = 'True if the button is pressed at that instant.';
cap3.p3 = 'was_pressed()';
cap3.p31 = 'True if the button was pressed since the last query.';
cap3.p4 = 'get_presses()';
cap3.p41 = 'how many times the button has been pressed.';
cap3.exe = '1: Traffic Light';
cap3.p5 = 'Program a one-light traffic light with the micro:bit:';
cap3.l31 = 'Button A';
cap3.l311 = 'proposal';
cap3.l312 = 'Image.NO';
cap3.l313 = '(red: STOP)';
cap3.l32 = 'Button B';
cap3.l321 = 'Image.ARROW_N';
cap3.l322 = '(green: GO)';
cap3.l33 = 'No button';
cap3.l331 = 'Image.DIAMOND';
cap3.l332 = '(yellow: WAIT)';
cap3.l41 = 'Basic level:';
cap3.l411 = 'only program the 2 buttons (without the \'no button\' state).';
cap3.l42 = 'Standard level:';
cap3.l421 = 'all 3 states as described.';
cap3.l43 = 'Advanced level:';
cap3.l431 = 'add a counter of people passing (variable that goes up by 1 with each press of button B).';
cap3.l44 = 'Oral:';
cap3.l441 = 'the student explains verbally what each state does instead of writing comments.';
cap3.l51 = 'Real context:';
cap3.l511 = 'propose that the numbers be meaningful data for the student: their shoe size and their age, today\\'s temperature and yesterday\\'s. Data with personal meaning increases engagement.';
cap3.exe2 = 'Exercise 2: Rock, Paper or Scissors';
cap3.p6 = 'Button A';
cap3.p61 = 'proposal';
cap3.p62 = ' Rock ';
cap3.p63 = 'Button B';
cap3.p64 = 'Paper';
cap3.p65 = 'Both';
cap3.p66 = 'Scissors';
cap3.p7 = 'The micro:bit chooses at random:';
cap3.p71 = 'import random';
cap3.p711 = 'to execute';
cap3.p712 = 'random.randint(0, 2)';
cap3.p8 = 'Show who wins or if there is a tie.';
cap3.l61 = 'Scaffolding (code with gaps):';
cap3.l611 = 'options = [\'Rock\',';
cap3.l612 = 'player = # Change according to button pressed';
cap3.l613 = 'machine = random.randint';
cap3.l614 = 'if player == machine:';
cap3.l615 = 'display.scroll';
cap3.l62 = 'Alternative:';
cap3.l621 = 'the student draws on paper the complete flow diagram of the game (without code) as evidence of understanding the logic.';
cap3.l71 = 'Interdependence:';
cap3.l711 = 'one student\\'s code doesn\\'t work without their partner\\'s. Interdependence is the driver of engagement.';
cap3.l72 = 'Debate:';
cap3.l721 = 'how is this like WhatsApp? What would happen if the channel (group) were not the same?';

// MODULES.cap4
const cap4 = merged.EDUCADORES_PAGE.MODULES.cap4;
cap4.hd1 = '4.1 The while loop';
cap4.p1 = 'A loop repeats a block of code as long as a condition is met. It is like a traffic light: if the light is red, stop; if it is green, go.';
cap4.l11 = 'Physical activity (unplugged):';
cap4.l111 = 'ask 5 students to stand in a line and tell them: \'repeat your name out loud WHILE there are people left in front of you\'. They have acted out a while loop.';
cap4.l12 = 'Analogy:';
cap4.l121 = 'a loop is like a washing machine drum: it spins over and over until it finishes (false condition).';
cap4.code1 = 'countdown.py';
cap4.l21 = 'The loop';
cap4.l211 = 'while';
cap4.l212 = 'keeps repeating while the condition is';
cap4.l213 = 'True';
cap4.l22 = 'CAUTION:';
cap4.l221 = 'if the condition never becomes';
cap4.l222 = 'False';
cap4.l223 = 'the loop is infinite and the program crashes.';
cap4.l23 = 'number -= 1';
cap4.l231 = 'is an abbreviation for';
cap4.l232 = 'number = number - 1';
cap4.hd2 = '4.2 The for loop';
cap4.code2 = 'for_loop.py';
cap4.p2 = 'range(n)';
cap4.p21 = 'generates numbers 0, 1, 2, ..., n-1.';
cap4.p3 = 'range(start, end)';
cap4.p31 = 'generates from start to end-1.';
cap4.p4 = 'range(start, end, step)';
cap4.p41 = 'allows going by 2s, 3s, or in reverse with a negative step.';
cap4.hd3 = '4.3 Animation: nested loops';
cap4.code3 = 'led_animation.py';
cap4.exe = ': Digital counter';
cap4.p5 = 'The counter shows 0, 1, 2... up to 9 and starts over (infinite loop).';
cap4.p6 = 'Each number is seen for 0.5 seconds.';
cap4.p7 = 'Extension:';
cap4.p71 = 'pressing button A stops the counter.';
cap4.l31 = 'Level 1 (Template):';
cap4.l311 = 'for i in range';
cap4.l312 = ': display.show(str';
cap4.l313 = 'sleep';
cap4.l32 = 'Level 2 (Standard):';
cap4.l321 = 'the exercise as described.';
cap4.l332 = 'range(9, -1, -1)';
cap4.l33 = 'Level 3 (Advanced):';
cap4.l331 = 'the counter jumps by 2s or 3s.';
cap4.l34 = 'Level 4 (Challenge):';
cap4.l341 = 'the counter jumps by 2s or 3s.';
cap4.l41 = 'Context choice:';
cap4.l411 = 'the student can program a \'soccer match timer\', a \'gym exercise counter\' or whatever connects with their interests.';
cap4.code4 = 'rain.py';

// MODULES.cap5
const cap5 = merged.EDUCADORES_PAGE.MODULES.cap5;
cap5.hd1 = '5.1 Lists: data collections';
cap5.p1 = 'A list stores several values in a single variable, accessible by their position (index, starting at 0).';
cap5.l11 = 'Physical activity:';
cap5.l111 = 'ask 5 students to stand in a line and number them from 0 to 4. Say: \'student number 2, what is your name?\'';
cap5.l112 = 'They have acted out accessing a list by index.';
cap5.l12 = 'Analogy:';
cap5.l121 = 'a list is like a numbered shopping list: it has items in order, and you can add, remove, or consult any position.';
cap5.code1 = 'basic_lists.py';
cap5.captable = 'Operations with lists';
cap5.tr11 = 'Operation';
cap5.tr12 = 'Example';
cap5.tr21 = 'Access by index';
cap5.tr22 = 'list[0], list[-1]';
cap5.tr221 = '(last)';
cap5.tr31 = 'Modify element';
cap5.tr32 = 'list[1] = \'new value\'';
cap5.tr41 = 'Add to end';
cap5.tr42 = 'list.append(\'new\')';
cap5.tr421 = 'or';
cap5.tr422 = 'add list[i]';
cap5.tr51 = 'Remove element';
cap5.tr52 = 'list.remove(\'value\')';
cap5.tr521 = 'or';
cap5.tr522 = 'del list[i]';
cap5.tr61 = 'Length';
cap5.tr62 = 'len(list)';
cap5.tr71 = 'Check membership';
cap5.tr72 = '\'element\' in list';
cap5.tr721 = 'returns';
cap5.tr722 = 'True';
cap5.tr723 = 'or';
cap5.tr724 = 'False';
cap5.tr81 = 'Sort';
cap5.tr82 = 'list.sort()';
cap5.hd2 = '5.2 Functions: code with its own name';
cap5.p2 = 'Functions encapsulate reusable code and give it a name. They are the first step towards modular programming.';
cap5.l21 = 'Metaphor:';
cap5.l211 = 'a function is like a recipe with a name. \'make_cake()\' groups all the steps; every time you want to make a cake, you just call the recipe.';
cap5.l22 = 'Diagram: ';
cap5.l221 = 'draw a rectangle with the name at the top, the inputs (parameters) with arrows entering from the left and the output (return) exiting from the right.';
cap5.code2 = 'functions.py';
cap5.hd3 = 'Function rules';
cap5.l31 = 'def function_name(parameters):';
cap5.l311 = 'function definition';
cap5.l32 = 'indented code';
cap5.l321 = 'function body';
cap5.l33 = 'return value';
cap5.l331 = 'optional: what it returns';
cap5.l34 = 'A function must be defined BEFORE being called.';
cap5.l35 = 'Parameters are local variables: they only exist inside the function.';
cap5.exe = ': Animation library';
cap5.p3 = 'Create 4 animation functions:';
cap5.l41 = 'celebrate()';
cap5.l411 = 'victory animation (3 images of 0.3 s each)';
cap5.l42 = 'fail()';
cap5.l421 = 'defeat animation';
cap5.l43 = 'countdown(n)';
cap5.l431 = 'counts from n to 0';
cap5.l44 = 'show_info()';
cap5.l441 = 'temperature + icon depending on value';
cap5.p4 = 'Write a main program that calls them in order.';
cap5.l51 = 'Level 1: Template:';
cap5.code3 = 'def celebrate():';
cap5.code4 = 'display.show';
cap5.code5 = 'sleep';
cap5.code6 = 'display.show';
cap5.l52 = 'Portfolio:';
cap5.l521 = 'the student documents their functions on a physical \'function card\': name, what it\\'s for, parameters, what it returns.';
cap5.l53 = 'Oral presentation: ';
cap5.l531 = 'student explains to the class how one of their functions works while executing it.';
cap5.l61 = 'Authorship:';
cap5.l611 = 'the student can name the functions whatever they want. It is not mandatory to name them exactly as in the statement.';
cap5.l62 = 'Connection:';
cap5.l621 = 'relate functions to videogame \'commands\':';
cap5.l622 = 'jump()';
cap5.l623 = 'attack()';
cap5.l624 = 'run()';
cap5.l625 = 'The concept is already in their previous experience.';

fs.writeFileSync('src/assets/i18n/en.json', JSON.stringify(merged, null, 2));
